routes/admin.php
<?php
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin'
], function () {
    Route::middleware('guest:admin')->group(function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login')->name('post.login');

        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')
            ->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')
            ->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')
            ->name('password.reset.token');
        Route::post('password/reset', 'ResetPasswordController@reset')
            ->name('password.reset');
    });

    Route::middleware('auth:admin')->group(function () {
        Route::post('logout', 'LoginController@adminLogout')->name('logout');

        /**
         * Home route
         */
        Route::get('/home', function () {
            return view('layouts.admin');
        })->name('home');

        /**
         * Category route
         */
        Route::resource('categories', 'CategoriesController');

        /**
         * Subcategory route
         */
        Route::get('subcategories/{categoryId}', 'CategoriesController@subCategory')->name('subcategory');

        /**
         * State route
         */
        Route::resource('states', 'StatesController');

        /**
         * City route
         */
        Route::resource('cities', 'CitiesController');

        /**
         * SignupQuestion route
         */
        Route::resource('signup_questions', 'SignupQuestionsController');

        /**
         * QuoteQuestion route
         */
        Route::resource('quote_questions', 'QuoteQuestionsController');

        /**
         * Tag route
         */
        Route::resource('tags', 'TagsController');

        /**
         * Service Provider Question route
         */
        Route::resource('provider-questions', 'ProviderQuestionsController');

        /**
         * Setting route
         */
        Route::get('settings', 'SettingsController@index');
        Route::patch('settings', 'SettingsController@update');

        Route::get('feedback', 'FeedbacksController@index');
        Route::get('feedback/{feedbackId}/show', 'FeedbacksController@show');

        Route::get('report', 'ReportsController@index');
        Route::get('report/{feedbackId}/show', 'ReportsController@show');

        Route::resource('category-slider-images', 'SliderImagesController');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['uses' => 'HomeController@index', 'as' => 'home']);

Route::group(['prefix' => 'api/v1', 'namespace' => 'Api'], function () {
    Route::get('signup-data', 'UsersController@signupData');

    Route::post('service-provider-signup', 'LoginController@serviceProviderSignup');
    Route::post('user-signup', 'LoginController@userSignup');
    Route::post('verify-user', 'LoginController@verifyUser');
    Route::post('resend-verify-otp', 'LoginController@resendVerifyOtp');
    Route::post('update-number', 'UsersController@updateNumber');
    Route::post('send-update-number-otp', 'UsersController@sendUpdateNumberOtp');

    Route::post('login', 'LoginController@login');
    Route::post('fb-login', 'LoginController@fbLogin');
    Route::post('google-login', 'LoginController@googleLogin');
    Route::post('twitter-login', 'LoginController@twitterLogin');

    Route::post('send-forgot-password-otp', 'ForgotPasswordController@sendOtp');
    Route::post('resend-forgot-password-otp', 'ForgotPasswordController@resendOtp');
    Route::post('reset-password', 'ForgotPasswordController@resetPassword');

    Route::get('categories', 'CategoriesController@categories');
    Route::get('sub-categories/{id}', 'CategoriesController@subCategories');

    Route::get('service-providers', 'UsersController@serviceProviders');
    Route::get('service-provider/{id}', 'UsersController@getServiceProviderDetail');

    Route::post('favourite-service-provider', 'UsersController@postFavouriteServiceProvider');
    Route::get('favourites/{serviceProviderId}', 'UsersController@getServiceProviderFavourites');

    Route::post('review', 'ReviewsController@addReview');
    Route::get('reviews/{userId}', 'ReviewsController@getReviews');

    Route::get('discover-service-providers', 'ServiceProviderController@discoverServiceProviders');

    Route::get('notifications/{userId}', 'NotificationController@getNotifications');

    Route::post('send-feedback', 'FeedbackController@postSendFeedback');
    Route::post('report', 'FeedbackController@postSendReport');

    Route::post('profile', 'UsersController@postProfile');
    Route::post('change-password', 'UsersController@changePassword');
    Route::post('change-location', 'UsersController@postChangeLocation');

    Route::get('quote-questions', 'QuestionsController@getQuoteQuestions');
    Route::post('quote-answer', 'AnswerController@postQuoteAnswer');

    Route::get('service-provider-jobs/{providerId}', 'JobsController@serviceProviderJobs');
    Route::get('provider-job-detail', 'JobsController@serviceProviderJobDetail');

    Route::get('service-provider-questions', 'QuestionsController@getServiceProviderQuestions');
    Route::post('service-provider-answers', 'AnswerController@postServiceProviderAnswers');

    Route::get('user-jobs/{userId}', 'JobsController@userJobs');
    Route::get('job-providers/{jobId}', 'JobsController@getJobProviders');
    Route::get('provider-answers', 'JobsController@providerAnswers');
    Route::post('accept-job', 'JobsController@acceptJob');
    Route::post('complete-job', 'JobsController@completeJob');

    Route::get('provider-accepted-jobs/{providerId}', 'JobsController@providerAcceptedJobs');
    Route::get('filter-providers', 'ServiceProviderController@filterProviders');

    Route::get('users', 'UsersController@allUsers');
    Route::get('reset-users', 'UsersController@resetUsers');
    Route::get('jobs', 'UsersController@allJobs');
    Route::get('delete-jobs', 'UsersController@deleteJobs');
    Route::get('delete-notifications', 'UsersController@deleteNotifications');
    Route::get('expire-job', 'UsersController@expireJobs');

    Route::post('update-provider-answers', 'ServiceProviderController@updateProviderAnswers');
    Route::post('logout', 'UsersController@logout');

    Route::post('send-notification', 'NotificationController@send');
    Route::get('send-notification-otp/{id}', 'NotificationController@sendotp');
    Route::get('update-number/{id}/{number}', 'NotificationController@updateNumber');
});

app/User.php
<?php

namespace App;

use App\Helpers\Enums\UserStatuses;
use App\Helpers\UpdateMediaTrait;
use App\Models\Role;
use App\Models\ServiceProviderFavourite;
use App\Models\UserReview;
use App\Models\UserRole;
use App\Notifications\AdminResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class User extends Authenticatable implements HasMediaConversions
{
    use HasApiTokens;
    use Notifiable;
    use HasRoles;
    use HasMediaTrait;
    use UpdateMediaTrait;

    protected $morphClass = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'username', 'password', 'mobile_no', 'profile'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $appends = ['profile_url'];

    /**
     * Set abbr attribute.
     *
     * @param string $value
     * @return void
     */
    public function setUsernameAttribute($value)
    {
        $this->attributes['username'] = str_slug($value, '_');
    }

    /**
     * Hash the password before saving
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * A search scope
     * @param $query
     * @param $search
     * @return
     */
    public function scopeSearch($query, $search) {
        return $query->where('name', 'like', '%'.$search.'%');
    }

    /**
     * An active users scope
     * @param $query
     * @param $search
     * @return
     */
    public function scopeActive($query) {
        return $query->where('status', UserStatuses::ACTIVE);
    }

    /**
     * Register image conversions
     */
    public function registerMediaConversions()
    {
        $this->addMediaConversion('avatar')
            ->width(200)
            ->height(200)
            ->fit('crop', 200, 200)
            ->performOnCollections('avatar');
    }

    /**
     * Doesnt have image scope
     */
    public function scopeDoesntHaveImage($query, $collection) {
        return $query->whereDoesntHave('media', function ($query) use($collection) {
            $query->whereCollectionName($collection);
        });
    }

    /**
     * Has image scope
     */
    public function scopeHasImage($query, $collection) {
        return $query->whereHas('media', function ($query) use($collection) {
            $query->whereCollectionName($collection);
        });
    }

    /**
     * Get the avatar url
     */
    public function getAvatarAttribute()
    {
        $avatar = $this->getFirstMediaUrl('avatar', 'avatar');
        return $avatar ? $avatar : asset(get_setting('default_avatar'));
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new AdminResetPassword($token));
    }

    /**
     * Get admin user url
     */
    public function getAdminAuthorUrlAttribute()
    {
        return Auth::check() && Auth::user()->can('update', $this) ?
            action('Admin\\UsersController@edit', $this) : '';
    }

    /**
     * Get admin user attribute
     */
    public function getAdminAuthorLinkAttribute()
    {
        $author_link = $this->admin_author_url;

        $html = $author_link ?  '<a href="' . $author_link . '" class="admin-author-link">' : '';
        $html .= $this->name;
        $html .= $author_link ? '</a>' : '';

        return $html;
    }

    /**
     * Custom username column for passport
     *
     * @param $username
     * @return mixed
     */
    public function findForPassport($username)
    {
        return $this->where('username', $username)
            ->whereStatus(UserStatuses::ACTIVE)
            ->first();
    }

    /**
     * Get the phone record associated with the customer.
     */
    public function phone()
    {
        return $this->hasOne('App\MobileNumber');
    }

    /**
     * Check if verified
     */
    public function getIsVerifiedAttribute()
    {
        //has a phone
        return !empty($this->phone);
    }

    /**
     * Verified scope
     */
    public function scopeVerified($query)
    {
        return $query->has('phone');
    }

    /**
     * Get mobile number attribute
     */
    public function getMobileNumberAttribute()
    {
        return $this->phone ? $this->phone->number : '';
    }

    /**
     * Check if active
     */
    public function getIsActiveAttribute()
    {
        return $this->status == UserStatuses::ACTIVE;
    }

    /**
     * Update phone
     *
     * @param MobileNumber $phone
     * @return static
     */
    public function updatePhone( MobileNumber $phone ) {

        //update if npt same
        if ( empty($this->phone) || !$this->phone->isSame($phone) ) {
            //first clear
            $this->clearPhone();
            $this->phone()->save($phone);
        }

        return $this;
    }

    /**
     * A phone search scope
     * @param $query
     * @param $search
     * @return
     */
    public function scopeHasPhone($query, $search) {
        return $query->whereHas('phone', function ($query) use ($search) {
                $query->whereNumber($search);
            });
    }

    /**
     * Clear phone
     */
    public function clearPhone() {
        $this->phone()->update(['user_id' => null]);
    }

    /**
     * Get role attribute
     */
    public function getRoleAttribute()
    {
        return $this->roles->first();
    }

    /**
     * Get Role name
     */
    public function getRoleNameAttribute()
    {
        return $this->role ? $this->role->description : '';
    }

    /**
     * A user has one business
     */
    public function business()
    {
        return $this->hasOne('App\Business');
    }

    /**
     * Get the business id attribute
     */
    public function getBusinessIdAttribute()
    {
        return $this->business ? $this->business->id : null;
    }

    public function attachRole(Role $role)
    {
        if (!UserRole::where('user_id', $this->id)->where('role_id', $role->id)->first()) {
             UserRole::create([
                 'user_id' => $this->id,
                 'role_id' => $role->id
             ]);
        }
    }

    public function reviews()
    {
        return $this->hasMany(UserReview::class)->with('reviewer');
    }

    public function getProfileUrlAttribute()
    {
        return isset($this->attributes['profile']) ?
            asset('images/users/' . $this->attributes['profile']) :
            asset('img/user.png');
    }

    public function favourites()
    {
        return $this->hasMany(ServiceProviderFavourite::class, 'service_provider_id', 'id')->with('user');
    }
}

resources/views/admin/oauth-clients/_actions.blade.php
<ul class="actions">
    @if ( isset($oauth_client) ) @can('delete', $oauth_client)
    <li><a href="#" data-request-url="{{ action('Admin\\OAuthClientsController@destroy', $oauth_client) }}" data-redirect-url="{{ action('Admin\\OAuthClientsController@index') }}" class="delete-link" title="Delete"><i class="zmdi zmdi-delete"></i></a></li>
    @endcan @endif

    @can('create', Laravel\Passport\Client::class)
    <li><a href="{{ action('Admin\\OAuthClientsController@create') }}" title="Add New"><i class="zmdi zmdi-plus"></i></a></li>
    @endcan

    @can('index', Laravel\Passport\Client::class)
    <li><a href="{{ action('Admin\\OAuthClientsController@index') }}" title="List All"><i class="zmdi zmdi-view-list-alt"></i></a></li>
    @endcan
</ul>

resources/views/admin/oauth-clients/_bulk.blade.php
<?php
$actions = [];

if ( Auth::user()->can('editOwn', Laravel\Passport\Client::class) ) {
    $actions['approve'] = __('Approve');
    $actions['revoke'] = __('Revoke');
}

if ( Auth::user()->can('deleteOwn', Laravel\Passport\Client::class) ) {
    $actions['delete'] = __('Delete');
}
?>

@include('admin.partials.bulk', ['actions' => $actions, 'model' => 'oauth_clients'])

resources/views/admin/oauth-clients/_filter.blade.php
<?php
use App\Http\Controllers\Admin\OAuthClientsController;
use Illuminate\Support\Facades\Input;
?>
<div class="row">
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('search', __('Search')) !!}
            <div class="fg-line">
                {!! Form::text('search', isset($search) ? $search : old('search'),
                ['class' => 'form-control jtk', 'placeholder' => __('Search..')]) !!}
            </div>
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('status', __('Status')) !!}
            <?php
            $selected_status = Input::get('status', old('status'));
            $statuses = ['' => ''] + \App\Helpers\Enums\OAuthClientStatuses::getLabels();

            ?>
            {!! Form::select('status', $statuses, $selected_status, ['class' => 'form-control selectpicker']) !!}
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('user', __('User')) !!}
            <?php
            $selected_user = Input::get('user', old('user'));
            ?>
            {!! Form::select('user', App\User::whereId($selected_user)->pluck('name', 'id'), $selected_user,
            ['class' => 'selectpicker-ajax form-control', 'data-url' => action('Api\\UsersController@index')]) !!}
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('personal_access', __('Personal Access')) !!}
            <?php
            $selected_val = Input::get('personal_access', old('personal_access'));
            $yes_no = [
                '' => '',
                '1' => __('Yes'),
                '0' => __('No'),
            ];

            ?>
            {!! Form::select('personal_access', $yes_no, $selected_val, ['class' => 'form-control selectpicker']) !!}
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('password', __('Password')) !!}
            <?php
            $selected_val = Input::get('password', old('password'));
            ?>
            {!! Form::select('password', $yes_no, $selected_val, ['class' => 'form-control selectpicker']) !!}
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('orderby', __('Order by')) !!}
            <?php
            $selected_orderby = Input::get('orderby', old('orderby'));
            $orderbys = ['' => ''] + OAuthClientsController::getOrderbys();

            ?>
            {!! Form::select('orderby', $orderbys, $selected_orderby, ['class' => 'form-control selectpicker']) !!}
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="form-group">
            {!! Form::label('order', __('Order')) !!}
            <?php
            $selected_order = Input::get('order', old('order'));
            $orders = ['' => ''] + OAuthClientsController::getOrders();

            ?>
            {!! Form::select('order', $orders, $selected_order, ['class' => 'form-control selectpicker']) !!}
        </div>
    </div>
    <div class="col-md-3">
        <div class="submit-group p-t-20">
            <button class="btn btn-success m-r-10" type="submit">{{ __('Filter') }}</button>
            <a href="{{ action('Admin\\OAuthClientsController@index') }}" class="btn btn-default">{{ __('Clear') }}</a>
        </div>
    </div>
</div>

resources/views/admin/oauth-clients/_form.blade.php
<div class="row">
    <div class="col-md-8">

        <div class="card">
            <div class="card-header">
                <h2>{{ __('Details') }}</h2>
            </div>
            <div class="card-body card-padding">
                <div class="{{ add_error_class($errors->has('name'), 'form-group fg-float') }}">
                    <div class="fg-line">
                        {!! Form::label('name', __('Name') . ' *', ['class' => 'fg-label']) !!}
                        {!! Form::text('name', old('name'), ['required' => 'required', 'class' => 'form-control fg-input']) !!}
                    </div>
                    @include('errors._list', ['error' => $errors->get('name')])
                </div>
                <div class="{{ add_error_class($errors->has('redirect'), 'form-group fg-float') }}">
                    <div class="fg-line">
                        {!! Form::label('redirect', __('Redirect'), ['class' => 'fg-label']) !!}
                        {!! Form::text('redirect', old('redirect'), ['class' => 'form-control fg-input']) !!}
                    </div>
                    @include('errors._list', ['error' => $errors->get('redirect')])
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-body card-padding">
                @if( isset($oauth_client) )
                    <div class="form-horizontal">
                        <div class="form-group">
                            {!! Form::label('client_id', __('Client ID'), ['class' => 'control-label col-lg-2 col-md-3']) !!}
                            <div class="col-lg-10 col-md-9">
                                <div class="fg-line">
                                    <span class="form-control fg-input">{{ $oauth_client->id }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('client_secret', __('Client Secret'), ['class' => 'control-label col-lg-2 col-md-3']) !!}
                            <div class="col-lg-10 col-md-9">
                                <div class="fg-line">
                                    <span class="form-control fg-input">{{ $oauth_client->secret }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="row">
                    <div class="col-lg-offset-2 col-md-offset-3 col-md-4">
                        <?php
                        $attribs = [];
                        $disabled = isset($oauth_client) ? 'disabled' : '';
                        if ( $disabled ) {
                            $attribs[$disabled] = $disabled;
                        }
                        ?>
                        <div class="checkbox {{ $disabled }}">
                            <label>
                                {!! Form::checkbox('personal_access_client', 1, old('personal_access_client'), $attribs) !!}
                                <i class="input-helper"></i>
                                {{ __('Personal Access Client') }}
                            </label>
                        </div>
                        @include('errors._list', ['error' => $errors->get('personal_access_client')])
                    </div>
                    <div class="col-md-4">
                        <div class="checkbox {{ $disabled }}">
                            <label>
                                {!! Form::checkbox('password_client', 1, old('password_client'), $attribs) !!}
                                <i class="input-helper"></i>
                                {{ __('Password Client') }}
                            </label>
                        </div>
                        @include('errors._list', ['error' => $errors->get('password_client')])
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2>{{ __('Approve') }}</h2>
            </div>
            <div class="card-body card-padding">
                @can('editOthers', Laravel\Passport\Client::class)
                    <div class="{{ add_error_class($errors->has('user'), 'form-group') }}">
                        {!! Form::label('user', __('User')) !!}
                        <?php
                        $selected_user = isset($oauth_client) ? $oauth_client->user_id : old('user');
                        $attribs = ['class' => 'selectpicker-ajax jtk-select form-control', 'data-url' => action('Api\\UsersController@index')];
                        if ( isset($oauth_client) ) {
                            $attribs['disabled'] = 'disabled';
                        }
                        ?>
                        {!! Form::select('user', App\User::whereId($selected_user)->pluck('name', 'id')->prepend('', ''), $selected_user, $attribs) !!}
                        @include('errors._list', ['error' => $errors->get('user')])
                    </div>
                @endcan

                <div class="form-group m-b-0">
                    @if( isset($oauth_client) )
                    <?php
                        $approve_btn_text = $oauth_client->revoked ? __('Approve') : __('Revoke');
                        $approve_btn_context = $oauth_client->revoked ? 'btn-primary' : 'btn-danger';
                    ?>
                    {!! Form::button($approve_btn_text, ['class' => 'm-b-5 btn '.$approve_btn_context, 'type' => 'submit',
                    'name' => 'revoke', 'value' => !$oauth_client->revoked]) !!}
                    {!! Form::button(__('Regenerate Client Secret'), ['class' => 'm-b-5 btn btn-warning', 'type' => 'submit',
                    'name' => 'regenerate', 'value' => '1']) !!}
                    @endif
                    {!! Form::button(__('Save'), ['class' => 'm-b-5 btn btn-success', 'type' => 'submit']) !!}
                    <a class="btn btn-default m-b-5"
                       href="{{ action('Admin\\OAuthClientsController@index') }}">{{ __('Cancel') }}</a>
                </div>
            </div>
        </div>

    </div>
</div>

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {

        });
    </script>
@endpush

resources/views/admin/oauth-clients/_list.blade.php
@foreach($oauth_clients as $oauth_client)
    <tr>
        <td>
            <div class="checkbox pull-left flip">
                <label>
                    <input data-check="oauth_clients" name="oauth_clients[]" value="{{ $oauth_client->id }}" type="checkbox" />
                    <i class="input-helper"></i>
                </label>
            </div>
        </td>
        <td>
            {{ $oauth_client->name }}
            @if( $oauth_client->revoked )
                <strong class="status revoked">
                    {{ '― Revoked' }}
                </strong>
            @endif
        </td>
        <td>
            @if( $oauth_client->user_id )
                <?php $user = App\User::find($oauth_client->user_id); ?>
                @if( $user )
                {!! $user->admin_author_link !!}
                @endif
            @endif
        </td>
        <td><i class="zmdi zmdi-{{ $oauth_client->personal_access_client ? 'check' : 'close' }}"></i></td>
        <td><i class="zmdi zmdi-{{ $oauth_client->password_client ? 'check' : 'close' }}"></i></td>
        <td>
            <div class="pull-right">
                <ul class="actions">
                    @can('delete', $oauth_client)
                        <li>
                            <a href="#" data-request-url="{{ action('Admin\\OAuthClientsController@destroy', $oauth_client) }}"
                               data-redirect-url="{{ Request::fullUrl() }}" class="delete-link" title="Delete"><i
                                        class="zmdi zmdi-delete"></i></a>
                        </li>
                    @endcan

                    @can('update', $oauth_client)
                        <li>
                            <a href="{{ action('Admin\\OAuthClientsController@edit', $oauth_client) }}" title="Edit"><i
                                        class="zmdi zmdi-edit"></i></a>
                        </li>
                    @endcan
                </ul>
            </div>
        </td>
    </tr>
@endforeach

resources/views/admin/oauth-clients/_table.blade.php
<div class="table-responsive">
    @if( empty($no_bulk) )
    {!! Form::open(['action' => ['Admin\\OAuthClientsController@bulk'], 'method' => 'PUT',
        'class' => 'delete-form']) !!}
    <div class="p-l-30 p-r-30 p-t-20 p-b-20">
        @include('admin.oauth-clients._bulk')
    </div>
    @endif
    <div class="dataTables_wrapper">
        <table class="table table-striped dataTable">
            <thead>
            <tr>
                <th>
                    <div class="checkbox pull-left flip">
                        <label>
                            <input data-all="oauth_clients" value="1" type="checkbox" />
                            <i class="input-helper"></i>
                        </label>
                    </div>
                </th>
                <th>{{ __('Name') }}</th>
                <th>{{ __('User') }}</th>
                <th>{{ __('Personal Access') }}</th>
                <th>{{ __('Password') }}</th>
            </tr>
            </thead>
            <tbody>
            @include('admin.oauth-clients._list')
            </tbody>
        </table>
        @if( empty($no_pagination) )
        {{  $oauth_clients->links('admin.partials.pagination') }}
        @endif
    </div>
    @if( empty($no_bulk) )
    {!! Form::close() !!}
    @endif
</div>

resources/views/admin/oauth-clients/create.blade.php
@extends('admin.oauth-clients.oauth-clients')

@section('page-title', __('New OAuth2 Client'))

@section('content')
    {!! Form::open(['action' => 'Admin\\OAuthClientsController@store', 'files' => true]) !!}
    @include('admin.oauth-clients._form')
    {!! Form::close() !!}
@endsection

resources/views/admin/oauth-clients/edit.blade.php
@extends('admin.oauth-clients.oauth-clients')

@section('page-title', __('Edit OAuth2 Client'))

@section('content')
    {!! Form::model($oauth_client, ['method' => 'PATCH', 'files' => true, 'action' => ['Admin\\OAuthClientsController@update', $oauth_client]]) !!}
    @include('admin.oauth-clients._form')
    {!! Form::close() !!}
@endsection

resources/views/admin/oauth-clients/index.blade.php
@extends('admin.oauth-clients.oauth-clients')

@section('page-title', $title)

@section('content')
    <div class="card">
        <div class="card-body card-padding">
            {!! Form::open(['action' => ['Admin\\OAuthClientsController@index'], 'method' => 'GET']) !!}
            @include('admin.oauth-clients._filter')
            {!! Form::close() !!}
        </div>
    </div>

    <div class="card">
        @include('admin.oauth-clients._table')
    </div>
@endsection

resources/views/admin/oauth-clients/oauth-clients.blade.php
@extends('layouts.admin')

@section('title', 'OAuth2 Clients')
@section('page-title', 'OAuthClients')

@section('top-search')
    @include('admin.partials.search-model', ['search_action' => 'Admin\\OAuthClientsController@index'])
@endsection

@section('model-actions')
    @include('admin.oauth-clients._actions')
@endsection